module.exports = [{
    baseId: 1,
    type: 'cpu',
    upgradeId: 11,
    defOption: true
  }, {
    baseId: 1,
    type: 'cpu',
    upgradeId: 12,
    defOption: false
  }, {
    baseId: 1,
    type: 'cpu',
    upgradeId: 13,
    defOption: false
  }, {
    baseId: 1,
    type: 'cpu',
    upgradeId: 14,
    defOption: false
  }, {
    baseId: 1,
    type: 'ram',
    upgradeId: 5,
    defOption: true
  }, {
    baseId: 1,
    type: 'ram',
    upgradeId: 7,
    defOption: false
  }, {
    baseId: 1,
    type: 'ram',
    upgradeId: 9,
    defOption: false
  }, {
    baseId: 1,
    type: 'hdd',
    upgradeId: 16,
    defOption: true
  }, {
    baseId: 1,
    type: 'hdd',
    upgradeId: 17,
    defOption: false
  }, {
    baseId: 1,
    type: 'hdd',
    upgradeId: 19,
    defOption: false
  }, {
    baseId: 2,
    type: 'cpu',
    upgradeId: 12,
    defOption: true
  }, {
    baseId: 2,
    type: 'cpu',
    upgradeId: 13,
    defOption: false
  }, {
    baseId: 2,
    type: 'cpu',
    upgradeId: 14,
    defOption: false
  }, {
    baseId: 2,
    type: 'ram',
    upgradeId: 6,
    defOption: true
  }, {
    baseId: 2,
    type: 'ram',
    upgradeId: 8,
    defOption: false
  }, {
    baseId: 2,
    type: 'ram',
    upgradeId: 10,
    defOption: false
  }, {
    baseId: 2,
    type: 'hdd',
    upgradeId: 16,
    defOption: true
  }, {
    baseId: 2,
    type: 'hdd',
    upgradeId: 17,
    defOption: false
  }, {
    baseId: 2,
    type: 'hdd',
    upgradeId: 18,
    defOption: false
  }, {
    baseId: 2,
    type: 'hdd',
    upgradeId: 19,
    defOption: false
  }, {
    baseId: 2,
    type: 'gpu',
    upgradeId: 20,
    defOption: true
  }, {
    baseId: 2,
    type: 'gpu',
    upgradeId: 23,
    defOption: false
  }, {
    baseId: 2,
    type: 'gpu',
    upgradeId: 21,
    defOption: false
  }


]
